// Flatten lib/main.js and its relative imports (a DAG) into one module at src/main.js.
// The platform CLI inlines only a tree; diamond imports are the norm here, so we do it ourselves.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { strip } from "./strip.mjs";
import { pack, UNPACK_SRC, UNPACK_NAME } from "./pack.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = path.join(ROOT, "lib", "main.js");
const OUT = path.join(ROOT, "src", "main.js");
const IMPORT_RE = /^\s*import\s+(?:[^;'"]*?\sfrom\s+)?["'](\.[^"']+)["'];?\s*$/gm;
const DECL_RE = /^(?:export\s+)?(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm;

const order = [];
const seen = new Set();
async function visit(file, stack = []) {
  const abs = path.resolve(file);
  if (seen.has(abs)) return;
  if (stack.includes(abs)) throw new Error(`Circular import: ${[...stack, abs].map((f) => path.relative(ROOT, f)).join(" -> ")}`);
  const src = await readFile(abs, "utf8");
  for (const m of src.matchAll(IMPORT_RE)) {
    const target = path.resolve(path.dirname(abs), m[1]);
    await visit(target.endsWith(".js") ? target : `${target}.js`, [...stack, abs]);
  }
  seen.add(abs);
  order.push({ abs, src });
}
await visit(ENTRY);

const declared = new Map();
const parts = [];
let packed = 0;
for (const { abs, src } of order) {
  const rel = path.relative(ROOT, abs).split(path.sep).join("/");
  const isEntry = abs === path.resolve(ENTRY);
  // ignore declarations that live inside template literals (the webview client source)
  const scan = src.replace(/`[\s\S]*?`/g, "``");
  for (const m of scan.matchAll(DECL_RE)) {
    const name = m[1];
    if (declared.has(name)) throw new Error(`Duplicate top-level name "${name}" in ${rel} (also in ${declared.get(name)})`);
    declared.set(name, rel);
  }
  let body = src.replace(IMPORT_RE, "");
  if (!isEntry) body = body.replace(/^export\s+(?=(?:async\s+)?(?:function|const|let|var|class)\s)/gm, "");
  else body = body.replace(/^export\s+(?=(?:const|let|var|class)\s)/gm, "");
  body = packTemplates(strip(body), rel);
  parts.push(`// ---- ${rel}` + String.fromCharCode(10) + body.trim() + String.fromCharCode(10));
}

// 大段的 String.raw 模板（客户端 CSS/JS）压缩后随包发出，模块加载时解回原文（见 tools/pack.mjs）。
// 解码器只发一份；压缩后反而更大的模板原样保留。
function packTemplates(body, rel) {
  const TAG = "String.raw`";
  let out = "", i = 0;
  const hoist = [];
  for (;;) {
    const s = body.indexOf(TAG, i);
    if (s < 0) { out += body.slice(i); break; }
    const e = body.indexOf("`", s + TAG.length);
    if (e < 0) throw new Error(`unterminated String.raw in ${rel}`);
    const raw = body.slice(s + TAG.length, e);
    out += body.slice(i, s);
    i = e + 1;
    if (raw.length < 4000) { out += TAG + raw + "`"; continue; }
    const p = pack(raw);
    if (Buffer.byteLength(p, "utf8") >= Buffer.byteLength(raw, "utf8")) { out += TAG + raw + "`"; continue; }
    const name = `WD_PK${packed++}`;
    if (declared.has(name) || declared.has(UNPACK_NAME)) throw new Error(`name ${name}/${UNPACK_NAME} already declared`);
    hoist.push(`const ${name} = ${UNPACK_NAME}(${TAG}${p}\`);`);
    out += name;
  }
  if (!hoist.length) return body;
  return (packed === hoist.length ? UNPACK_SRC + "\n" : "") + hoist.join("\n") + "\n" + out;
}
const out = `// GENERATED by tools/build.mjs — edit lib/ instead.\n${parts.join("\n")}`;
await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, out, "utf8");
const bytes = Buffer.byteLength(out, "utf8");
console.log(`bundled ${order.length} modules -> ${path.relative(ROOT, OUT)} (${(bytes / 1024).toFixed(1)} KB)`);
if (bytes > 512 * 1024) { console.error("bundle exceeds 512 KB"); process.exit(1); }
